[package]
name = "dsp-logtail"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0", features = ["fs", "ioctl", "poll"] }
memmap2 = "0"
thiserror = "2"
chrono = "0.4"

[profile.release]
strip = true
lto = true